# Generated by Django 5.0.2 on 2025-04-12 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_referred_by_customuser_referrer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=18)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["referrer", "level"],
                        name="users_refer_referre_c5c85c_idx",
                    ),
                    models.Index(
                        fields=["referred_user"], name="users_refer_referre_38b969_idx"
                    ),
                ],
                "unique_together": {("referrer", "referred_user", "level")},
            },
        ),
    ]
