# Generated by Django 5.0.2 on 2025-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_referral_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/deposit_screenshots/"
            ),
        ),
    ]
