version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # Persist db.sqlite3 on the host
      - static_volume:/app/static
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: