"""
Django settings for nftvault project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "crispy_forms",
    "crispy_bootstrap5",
    "corsheaders",
    "users",
    'marketplace.apps.MarketplaceConfig',
    "mlm",
    "investments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nftvault.urls"
LOGIN_REDIRECT_URL = 'marketplace:home'
# LOGIN_REDIRECT_URL = 'users:profile'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "nftvault.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login/Logout URLs
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Web3 Configuration
WEB3_PROVIDER_URI = os.getenv('WEB3_PROVIDER_URI', 'http://localhost:8545')

# MLM Commission Rates
DIRECT_REFERRAL_RATE = 0.10  # 10%
SECOND_LEVEL_RATE = 0.05    # 5%

# Email configuration
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # Or your email provider
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER='developeracount211@gmail.com'
# EMAIL_HOST_PASSWORD = 'fbidghkpveretclw'
# DEFAULT_FROM_EMAIL = 'NFTVault <your-email@gmail.com>'

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.zoho.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER='infoafiliados@andacol.com' 
# 'developeracount211@gmail.com'
EMAIL_HOST_PASSWORD='sLtahhedKXCb' 


# Reward System Configuration
REWARD_TIERS = {
    'SILVER': {
        'min_volume': 5,  # ETH
        'cashback': 0.02,
        'staking_multiplier': 1.2,
        'platform_fee_discount': 0.1
    },
    'GOLD': {
        'min_volume': 15,
        'cashback': 0.035,
        'staking_multiplier': 1.5,
        'platform_fee_discount': 0.25
    },
    'DIAMOND': {
        'min_volume': 50,
        'cashback': 0.05,
        'staking_multiplier': 2.0,
        'platform_fee_discount': 1.0  # 100% discount
    }
}

# Staking Pool Configuration
STAKING_POOLS = {
    'QUICK': {
        'duration': 7,  # days
        'base_apy': 0.10,  # 10%
    },
    'STANDARD': {
        'duration': 30,
        'base_apy': 0.15,
    },
    'PREMIUM': {
        'duration': 90,
        'base_apy': 0.25,
    },
    'DIAMOND': {
        'duration': 180,
        'base_apy': 0.40,
    }
}

# MLM Commission Structure
MLM_COMMISSION = {
    'LEVEL_1': 0.12,  # 12%
    'LEVEL_2': 0.06,  # 6%
    'LEVEL_3': 0.03,  # 3%
    'TEAM_VOLUME_BONUS': 0.05,
    'LEADERSHIP_BONUS': 0.03,
    'GLOBAL_POOL': 0.02
}
