# Generated by Django 5.0.2 on 2025-03-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="nfts/")),
                ("token_id", models.CharField(max_length=255, unique=True)),
                ("contract_address", models.CharField(max_length=42)),
                (
                    "price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                ("is_for_sale", models.BooleanField(default=False)),
                ("is_staked", models.BooleanField(default=False)),
                (
                    "staking_rewards",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("STAKE", "Stake"),
                            ("UNSTAKE", "Unstake"),
                            ("COMMISSION", "Commission"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                (
                    "transaction_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
