# Generated by Django 5.0.2 on 2025-03-31 01:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="boost_multiplier",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="nft",
            name="last_trade_price",
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="nft",
            name="price_change_24h",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="nft",
            name="rarity_level",
            field=models.CharField(
                choices=[
                    ("COMMON", "Common"),
                    ("RARE", "Rare"),
                    ("EPIC", "Epic"),
                    ("LEGENDARY", "Legendary"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nft",
            name="total_trades",
            field=models.IntegerField(default=0),
        ),
    ]
