# Generated by Django 5.0.2 on 2025-04-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_transaction_status_alter_transaction_seller"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eth_balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                (
                    "usdt_balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                (
                    "eth_deposit_address",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                (
                    "usdt_deposit_address",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
