# Generated by Django 5.0.2 on 2025-04-06 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_nft_commission_rate_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("ETH", "Ethereum"), ("USDT", "Tether (USDT)")],
                default="ETH",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="nft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="marketplace.nft",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("BUY", "Buy"),
                    ("SELL", "Sell"),
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("COMMISSION", "Commission"),
                ],
                max_length=10,
            ),
        ),
    ]
