# Generated by Django 5.0.2 on 2025-04-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_transaction_currency_alter_transaction_nft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="depositAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eth_deposit_address",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                (
                    "usdt_deposit_address",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
            ],
        ),
    ]
