# Generated by Django 5.0.2 on 2025-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_depositaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositaddress",
            name="eth_deposit_address",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name="depositaddress",
            name="usdt_deposit_address",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
