# Generated by Django 5.0.2 on 2025-04-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_alter_depositaddress_eth_deposit_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="withdraw_address",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
