# Generated by Django 5.0.2 on 2025-04-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_transaction_withdraw_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
