# Generated by Django 5.0.2 on 2025-04-10 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_nft_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="staking_number_of_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nftownership",
            name="frozen_amount",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="nftownership",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nftownership",
            name="remaing_day_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nftownership",
            name="total_commission_earned",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name="CommissionClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                ("claim_date", models.DateTimeField(blank=True, null=True)),
                ("is_claimed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_claims",
                        to="marketplace.nftownership",
                    ),
                ),
            ],
        ),
    ]
