# Generated by Django 5.0.2 on 2025-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_nft_staking_number_of_days_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nftownership",
            old_name="remaing_day_number",
            new_name="day_number",
        ),
        migrations.AddField(
            model_name="nftownership",
            name="commission_claim_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nftownership",
            name="remaining_day_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nftownership",
            name="today_commission_claimed",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
