# Generated by Django 5.0.2 on 2025-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0014_wallet_created_at_wallet_payment_type_wallet_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="deposit_screenshots/"
            ),
        ),
    ]
