# Generated by Django 5.0.2 on 2025-03-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlm", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staking",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
